import slugify from "slugify";

import { Data, IAgentInput, IPropertyInput } from "@/types";

const agents: IAgentInput[] = [
  {
    image: "/images/agents/agent1.png",
    name: "Patricia Tullert",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent2.png",
    name: "Daryl Hawker",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent3.png",
    name: "Amado Smith",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent4.png",
    name: "Kaitlyn Gonzalez",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent5.png",
    name: "Grover Robinson",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent6.png",
    name: "Karen Sorensen",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent7.png",
    name: "Jawhar Shamil Naser",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent8.png",
    name: "Juana Douglass",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent9.png",
    name: "Jerry Schenck",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent10.png",
    name: "Vera Levesque",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent11.png",
    name: "Sofia Gomes",
    phone: "0123 456 78910",
  },
  {
    image: "/images/agents/agent12.png",
    name: "Raymond Hood",
    phone: "0123 456 78910",
  },
];

const properties: IPropertyInput[] = [
  {
    type: "house",
    name: "house 1",
    slug: slugify("house 1"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house1.jpg",
    country: "United States",
    address: "7240C Argyle St. Lawndale, CA 90260",
    bedrooms: 6,
    bathrooms: 3,
    surface: 4200,
    year: 2020,
    price: 210000,
    agent: {
      image: "/images/agents/agent1.png",
      name: "Patricia Tullert",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 2",
    slug: slugify("house 2"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house2.jpg",
    country: "Canada",
    address: "798 Talbot St. Bridgewater, NJ 08807",
    bedrooms: 6,
    bathrooms: 3,
    surface: 4200,
    year: 2011,
    price: 140000,
    agent: {
      image: "/images/agents/agent2.png",
      name: "Daryl Hawker",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 3",
    slug: slugify("house 3"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house3.jpg",
    country: "United States",
    address: "2 Glen Creek St. Alexandria, VA 22304",
    bedrooms: 6,
    bathrooms: 3,
    surface: 4200,
    year: 2016,
    price: 170000,
    agent: {
      image: "/images/agents/agent3.png",
      name: "Amado Smith",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 4",
    slug: slugify("house 4"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house4.jpg",
    country: "Canada",
    address: "84 Woodland St. Cocoa, FL 32927",
    bedrooms: 6,
    bathrooms: 3,
    surface: 4200,
    year: 2013,
    price: 220000,
    agent: {
      image: "/images/agents/agent4.png",
      name: "Kaitlyn Gonzalez",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 5",
    slug: slugify("house 5"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house5.jpg",
    country: "United States",
    address: "28 Westport Dr. Warminster, PA 18974",
    bedrooms: 5,
    bathrooms: 3,
    surface: 4200,
    year: 2016,
    price: 210000,
    agent: {
      image: "/images/agents/agent5.png",
      name: "Grover Robinson",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 6",
    slug: slugify("house 6"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house6.jpg",
    country: "Canada",
    address: "32 Pawnee Street Butte, MT 59701",
    bedrooms: 6,
    bathrooms: 3,
    surface: 6200,
    year: 2011,
    price: 295000,
    agent: {
      image: "/images/agents/agent6.png",
      name: "Karen Sorensen",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 7",
    slug: slugify("house 7"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house7.jpg",
    country: "Canada",
    address: "7240C Argyle St. Lawndale, CA 90260",
    bedrooms: 5,
    bathrooms: 3,
    surface: 3200,
    year: 2015,
    price: 117000,
    agent: {
      image: "/images/agents/agent10.png",
      name: "Vera Levesque",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 8",
    slug: slugify("house 8"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house8.jpg",
    country: "Canada",
    address: "798 Talbot St. Bridgewater, NJ 08807",
    bedrooms: 7,
    bathrooms: 2,
    surface: 2200,
    year: 2019,
    price: 145000,
    agent: {
      image: "/images/agents/agent11.png",
      name: "Sofia Gomes",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 9",
    slug: slugify("house 9"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house9.jpg",
    country: "United States",
    address: "2 Glen Creek St. Alexandria, VA 22304",
    bedrooms: 4,
    bathrooms: 4,
    surface: 4600,
    year: 2015,
    price: 139000,
    agent: {
      image: "/images/agents/agent12.png",
      name: "Raymond Hood",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 10",
    slug: slugify("house 10"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house10.jpg",
    country: "Canada",
    address: "84 Woodland St. Cocoa, FL 32927",
    bedrooms: 5,
    bathrooms: 2,
    surface: 5200,
    year: 2014,
    price: 180000,
    agent: {
      image: "/images/agents/agent1.png",
      name: "Patricia Tullert",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 11",
    slug: slugify("house 11"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house11.jpg",
    country: "United States",
    address: "28 Westport Dr. Warminster, PA 18974",
    bedrooms: 5,
    bathrooms: 2,
    surface: 3200,
    year: 2011,
    price: 213000,
    agent: {
      image: "/images/agents/agent2.png",
      name: "Daryl Hawker",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "house 12",
    slug: slugify("house 12"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house12.jpg",
    country: "Canada",
    address: "32 Pawnee Street Butte, MT 59701",
    bedrooms: 4,
    bathrooms: 3,
    surface: 5200,
    year: 2011,
    price: 221000,
    agent: {
      image: "/images/agents/agent3.png",
      name: "Amado Smith",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "Villa 1",
    slug: slugify("Villa 1"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house13.jpg",
    country: "United States",
    address: "28 Westport Dr. Miami, FL 33101",
    bedrooms: 4,
    bathrooms: 3,
    surface: 15450,
    year: 2011,
    price: 221000,
    agent: {
      image: "/images/agents/agent4.png",
      name: "Kaitlyn Gonzalez",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "Villa 2",
    slug: slugify("Villa 2"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house14.jpg",
    country: "Spain",
    address: "28 Maritimo El Pedrigal, Malaga 29018",
    bedrooms: 4,
    bathrooms: 3,
    surface: 12450,
    year: 2016,
    price: 341000,
    agent: {
      image: "/images/agents/agent5.png",
      name: "Grover Robinson",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "Villa 3",
    slug: slugify("Villa 3"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house15.jpg",
    country: "Philippines",
    address: "28 Aquino Blvd San Roque, Manila 10110",
    bedrooms: 6,
    bathrooms: 4,
    surface: 18250,
    year: 2017,
    price: 295000,
    agent: {
      image: "/images/agents/agent6.png",
      name: "Karen Sorensen",
      phone: "0123 456 78910",
    },
  },
  {
    type: "house",
    name: "Villa 4",
    slug: slugify("Villa 4"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/houses/house16.jpg",
    country: "Canada",
    address: "211 LaSalle Boul. Monreal, H",
    bedrooms: 4,
    bathrooms: 3,
    surface: 15450,
    year: 2011,
    price: 221000,
    agent: {
      image: "/images/agents/agent7.png",
      name: "Jawhar Shamil Naser",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 1",
    slug: slugify("apartament 1"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment1.jpg",
    country: "Canada",
    address: "32 Pawnee Street Butte, MT 59701",
    bedrooms: 2,
    bathrooms: 1,
    surface: 1200,
    year: 2012,
    price: 95000,
    agent: {
      image: "/images/agents/agent7.png",
      name: "Jawhar Shamil Naser",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 2",
    slug: slugify("apartament 2"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment2.jpg",
    country: "United States",
    address: "28 Westport Dr. Warminster, PA 18974",
    bedrooms: 3,
    bathrooms: 1,
    surface: 1000,
    year: 2011,
    price: 65000,
    agent: {
      image: "/images/agents/agent8.png",
      name: "Juana Douglass",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 3",
    slug: slugify("apartament 3"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment3.jpg",
    country: "United States",
    address: "84 Woodland St. Cocoa, FL 32927",
    bedrooms: 2,
    bathrooms: 1,
    surface: 1100,
    year: 2011,
    price: 65000,
    agent: {
      image: "/images/agents/agent9.png",
      name: "Jerry Schenck",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 4",
    slug: slugify("apartament 4"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment4.jpg",
    country: "Canada",
    address: "32 Pawnee Street Butte, MT 59701",
    bedrooms: 2,
    bathrooms: 1,
    surface: 1300,
    year: 2011,
    price: 51000,
    agent: {
      image: "/images/agents/agent4.png",
      name: "Kaitlyn Gonzalez",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 5",
    slug: slugify("apartament 5"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment5.jpg",
    country: "United States",
    address: "28 Westport Dr. Warminster, PA 18974",
    bedrooms: 3,
    bathrooms: 1,
    surface: 1000,
    year: 2012,
    price: 61000,
    agent: {
      image: "/images/agents/agent5.png",
      name: "Grover Robinson",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 6",
    slug: slugify("apartament 6"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment6.jpg",
    country: "Canada",
    address: "84 Woodland St. Cocoa, FL 32927",
    bedrooms: 3,
    bathrooms: 1,
    surface: 1200,
    year: 2010,
    price: 68000,
    agent: {
      image: "/images/agents/agent6.png",
      name: "Karen Sorensen",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 7",
    slug: slugify("apartament 7"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment7.jpg",
    country: "Canada",
    address: "84 Drive St. Toronto, M",
    bedrooms: 3,
    bathrooms: 1,
    surface: 1200,
    year: 2010,
    price: 56000,
    agent: {
      image: "/images/agents/agent10.png",
      name: "Vera Levesque",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 8",
    slug: slugify("apartament 8"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment8.jpg",
    country: "France",
    address: "124 Les Charron, Charente-Maritime, 17230",
    bedrooms: 3,
    bathrooms: 1,
    surface: 5100,
    year: 2010,
    price: 354000,
    agent: {
      image: "/images/agents/agent11.png",
      name: "Sofia Gomes",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 9",
    slug: slugify("apartament 9"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment9.jpg",
    country: "United States",
    address: "2 Glen Creek St. Alexandria, VA 22304",
    bedrooms: 4,
    bathrooms: 4,
    surface: 4600,
    year: 2015,
    price: 139000,
    agent: {
      image: "/images/agents/agent12.png",
      name: "Raymond Hood",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 10",
    slug: slugify("apartament 10"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment10.jpg",
    country: "Canada",
    address: "84 Woodland St. Cocoa, FL 32927",
    bedrooms: 5,
    bathrooms: 2,
    surface: 3200,
    year: 2019,
    price: 135000,
    agent: {
      image: "/images/agents/agent1.png",
      name: "Patricia Tullert",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 11",
    slug: slugify("apartament 11"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment11.jpg",
    country: "United States",
    address: "28 Westport Dr. Warminster, PA 18974",
    bedrooms: 5,
    bathrooms: 2,
    surface: 3200,
    year: 2011,
    price: 213000,
    agent: {
      image: "/images/agents/agent2.png",
      name: "Daryl Hawker",
      phone: "0123 456 78910",
    },
  },
  {
    type: "apartament",
    name: "apartament 12",
    slug: slugify("apartament 12"),
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: "/images/apartments/apartment12.jpg",
    country: "Canada",
    address: "32 Pawnee Street Butte, MT 59701",
    bedrooms: 4,
    bathrooms: 3,
    surface: 5200,
    year: 2013,
    price: 221000,
    agent: {
      image: "/images/agents/agent3.png",
      name: "Amado Smith",
      phone: "0123 456 78910",
    },
  },
];

const data: Data = {
  agents,
  properties,
};

export default data;
